---
# Homepage Settings Configuration
# Documentation: https://gethomepage.dev/configs/settings/

title: Home Server

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 100
  brightness: 50
  opacity: 50

theme: dark
color: slate

headerStyle: boxed

layout:
  Infrastructure:
    style: row
    columns: 3
  Medias:
    style: row
    columns: 3
  Automatisation:
    style: row
    columns: 1
  Outils:
    style: row
    columns: 2
  Metriques:
    style: row
    columns: 2
